### ISSUE TITLE
Interaction disabled on Retina MacBook Pro.

### ISSUE THREAD

**Issue by dsc** [mbostock/stack#2]
I don't know if how recent this change is, but this iOS check now returns true for Chrome (I've got 20.0.1180.79):

``` js
// Don't do anything fancy for iOS.
if (section.style("display") == "block")
  return;
```

I looked at stack a few weeks ago, and it worked then. This might be due to a beta channel update, but I can't for the life of me figure out where they moved that information in the Chrome about dialog.

**Comment by mbostock** [comment]
What OS? I just tested on Version 21.0.1180.75 / Mac OS X 10.8, and it works fine.

**Comment by dsc** [comment]
10.7.4; new 15" Retina MBP.

**Comment by mbostock** [comment]
Yeah, the problem is the CSS media query for iPhone 4 now matches the MacBook Retina display.

**Comment by dsc** [comment]
Ahh -- that is good to know. The point of disabling interaction is that iOS doesn't scroll, yes? (Instead panning the viewport?) Perhaps test if body dimensions match window dimensions?

**Comment by mbostock** [comment]
This has been fixed.
