### ISSUE TITLE
location.hash support

### ISSUE THREAD

**Issue by tmcw** [mbostock/stack#6]
Using stack for a presentation, and it's working great. It would be great for it to use hashes for slide indices so that you can link to individual slides - I could whip up a pull req if that sounds good.

**Comment by mbostock** [comment]
Sounds great! Would love this feature. My only request is that you use location.replace to avoid polluting the history (the back button should leave the page entirely, not go between slides), and only update the hash when the slide changes to avoid address bar flickering.

Another feature I would love to see is the ESC button would zoom out and display all slides in a flow layout. [Reveal.js](http://lab.hakim.se/reveal-js) has this lovely feature and I’ve always been jealous. ;)
